# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: linearmaps.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'linearmaps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10linearmaps.proto\x12\nlinearmaps\"\'\n\x06Matrix\x12\x1d\n\x04rows\x18\x01 \x03(\x0b\x32\x0f.linearmaps.Row\"\x15\n\x03Row\x12\x0e\n\x06values\x18\x01 \x03(\x01\"?\n\x0c\x41pplyRequest\x12\x1f\n\x03map\x18\x01 \x01(\x0b\x32\x12.linearmaps.Matrix\x12\x0e\n\x06vector\x18\x02 \x03(\x01\"\x1f\n\rApplyResponse\x12\x0e\n\x06result\x18\x01 \x03(\x01\"Y\n\x10\x42inaryMapRequest\x12!\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x12.linearmaps.Matrix\x12\"\n\x06second\x18\x02 \x01(\x0b\x32\x12.linearmaps.Matrix\"?\n\x0bMapResponse\x12\"\n\x06result\x18\x01 \x01(\x0b\x32\x12.linearmaps.Matrix\x12\x0c\n\x04note\x18\x02 \x01(\t\"?\n\x0cScaleRequest\x12\x1f\n\x03map\x18\x01 \x01(\x0b\x32\x12.linearmaps.Matrix\x12\x0e\n\x06scalar\x18\x02 \x01(\x01\"V\n\x0e\x43omposeRequest\x12!\n\x05outer\x18\x01 \x01(\x0b\x32\x12.linearmaps.Matrix\x12!\n\x05inner\x18\x02 \x01(\x0b\x32\x12.linearmaps.Matrix\".\n\x0bZeroRequest\x12\x1f\n\x03map\x18\x01 \x01(\x0b\x32\x12.linearmaps.Matrix\"0\n\x0cZeroResponse\x12\r\n\x05holds\x18\x01 \x01(\x08\x12\x11\n\tt_of_zero\x18\x02 \x03(\x01\x32\xc3\x02\n\nLinearMaps\x12<\n\x05\x41pply\x12\x18.linearmaps.ApplyRequest\x1a\x19.linearmaps.ApplyResponse\x12<\n\x03\x41\x64\x64\x12\x1c.linearmaps.BinaryMapRequest\x1a\x17.linearmaps.MapResponse\x12:\n\x05Scale\x12\x18.linearmaps.ScaleRequest\x1a\x17.linearmaps.MapResponse\x12>\n\x07\x43ompose\x12\x1a.linearmaps.ComposeRequest\x1a\x17.linearmaps.MapResponse\x12=\n\x08SendZero\x12\x17.linearmaps.ZeroRequest\x1a\x18.linearmaps.ZeroResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'linearmaps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATRIX']._serialized_start=32
  _globals['_MATRIX']._serialized_end=71
  _globals['_ROW']._serialized_start=73
  _globals['_ROW']._serialized_end=94
  _globals['_APPLYREQUEST']._serialized_start=96
  _globals['_APPLYREQUEST']._serialized_end=159
  _globals['_APPLYRESPONSE']._serialized_start=161
  _globals['_APPLYRESPONSE']._serialized_end=192
  _globals['_BINARYMAPREQUEST']._serialized_start=194
  _globals['_BINARYMAPREQUEST']._serialized_end=283
  _globals['_MAPRESPONSE']._serialized_start=285
  _globals['_MAPRESPONSE']._serialized_end=348
  _globals['_SCALEREQUEST']._serialized_start=350
  _globals['_SCALEREQUEST']._serialized_end=413
  _globals['_COMPOSEREQUEST']._serialized_start=415
  _globals['_COMPOSEREQUEST']._serialized_end=501
  _globals['_ZEROREQUEST']._serialized_start=503
  _globals['_ZEROREQUEST']._serialized_end=549
  _globals['_ZERORESPONSE']._serialized_start=551
  _globals['_ZERORESPONSE']._serialized_end=599
  _globals['_LINEARMAPS']._serialized_start=602
  _globals['_LINEARMAPS']._serialized_end=925
# @@protoc_insertion_point(module_scope)
