# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import linearmaps_pb2 as linearmaps__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in linearmaps_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LinearMapsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Apply = channel.unary_unary(
                '/linearmaps.LinearMaps/Apply',
                request_serializer=linearmaps__pb2.ApplyRequest.SerializeToString,
                response_deserializer=linearmaps__pb2.ApplyResponse.FromString,
                _registered_method=True)
        self.Add = channel.unary_unary(
                '/linearmaps.LinearMaps/Add',
                request_serializer=linearmaps__pb2.BinaryMapRequest.SerializeToString,
                response_deserializer=linearmaps__pb2.MapResponse.FromString,
                _registered_method=True)
        self.Scale = channel.unary_unary(
                '/linearmaps.LinearMaps/Scale',
                request_serializer=linearmaps__pb2.ScaleRequest.SerializeToString,
                response_deserializer=linearmaps__pb2.MapResponse.FromString,
                _registered_method=True)
        self.Compose = channel.unary_unary(
                '/linearmaps.LinearMaps/Compose',
                request_serializer=linearmaps__pb2.ComposeRequest.SerializeToString,
                response_deserializer=linearmaps__pb2.MapResponse.FromString,
                _registered_method=True)
        self.SendZero = channel.unary_unary(
                '/linearmaps.LinearMaps/SendZero',
                request_serializer=linearmaps__pb2.ZeroRequest.SerializeToString,
                response_deserializer=linearmaps__pb2.ZeroResponse.FromString,
                _registered_method=True)


class LinearMapsServicer:
    """Missing associated documentation comment in .proto file."""

    def Apply(self, request, context):
        """T(v)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """S + T
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scale(self, request, context):
        """λT
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compose(self, request, context):
        """outer ∘ inner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendZero(self, request, context):
        """T(0) = 0 ?
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinearMapsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=linearmaps__pb2.ApplyRequest.FromString,
                    response_serializer=linearmaps__pb2.ApplyResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=linearmaps__pb2.BinaryMapRequest.FromString,
                    response_serializer=linearmaps__pb2.MapResponse.SerializeToString,
            ),
            'Scale': grpc.unary_unary_rpc_method_handler(
                    servicer.Scale,
                    request_deserializer=linearmaps__pb2.ScaleRequest.FromString,
                    response_serializer=linearmaps__pb2.MapResponse.SerializeToString,
            ),
            'Compose': grpc.unary_unary_rpc_method_handler(
                    servicer.Compose,
                    request_deserializer=linearmaps__pb2.ComposeRequest.FromString,
                    response_serializer=linearmaps__pb2.MapResponse.SerializeToString,
            ),
            'SendZero': grpc.unary_unary_rpc_method_handler(
                    servicer.SendZero,
                    request_deserializer=linearmaps__pb2.ZeroRequest.FromString,
                    response_serializer=linearmaps__pb2.ZeroResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'linearmaps.LinearMaps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('linearmaps.LinearMaps', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LinearMaps:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linearmaps.LinearMaps/Apply',
            linearmaps__pb2.ApplyRequest.SerializeToString,
            linearmaps__pb2.ApplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linearmaps.LinearMaps/Add',
            linearmaps__pb2.BinaryMapRequest.SerializeToString,
            linearmaps__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linearmaps.LinearMaps/Scale',
            linearmaps__pb2.ScaleRequest.SerializeToString,
            linearmaps__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linearmaps.LinearMaps/Compose',
            linearmaps__pb2.ComposeRequest.SerializeToString,
            linearmaps__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendZero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linearmaps.LinearMaps/SendZero',
            linearmaps__pb2.ZeroRequest.SerializeToString,
            linearmaps__pb2.ZeroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
